import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const nike = localFont({
  src: "./fonts/Supreme_Complete/Fonts/OTF/Supreme-Medium.otf",
  variable: "--font-supreme",
  weight: "100 900",
});

const nikebold = localFont({
  src: "./fonts/Supreme_Complete/Fonts/OTF/Supreme-Bold.otf",
  variable: "--font-supreme-bold",
  weight: "100 900",
});

const nikethin = localFont({
  src: "./fonts/Supreme_Complete/Fonts/OTF/Supreme-Thin.otf",
  variable: "--font-supreme-thin",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Nike",
  description: "Generated by Vinolia Masango",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nike.variable} ${nikebold.variable} ${nikethin.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
